### ISSUE TITLE
Cannot build the database using get_igmspec

### ISSUE THREAD

**Issue by ntejos** [specdb/igmspec#67]
The error is 
```
(astroconda)ntejos@arrakis:~/python/igmspec/DB$ get_igmspec 
Traceback (most recent call last):
  File "/home/ntejos/anaconda/envs/astroconda/bin/get_igmspec", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ntejos/python/igmspec/bin/get_igmspec", line 12, in <module>
    import igmspec.scripts.get_igmspec as get_igmspec
ImportError: No module named get_igmspec
```

Seems some sort of compatibility issue w/r to the old igmspec implementation.

**Comment by profxj** [comment]
get_igmspec is no longer in igmspec.
Only in specdb.

You probably need to remove the script from your anaconda distribution (or insure that
the one from specdb over-writes it).

**Comment by ntejos** [comment]
I see; so if I wish to install igm_spec and load the database, I also need to install specdb?

**Comment by profxj** [comment]
No, you only need to install specdb.  

igmspec software is only for building the igmspec database.

**Comment by ntejos** [comment]
Got it; thanks for the clarification. Will close the 'issue'.
